"use client";

import { FormEvent, useEffect, useState } from "react";
import { CircleDollarSign, Crown, Gift, Package, Pencil, Plus, Save, ShieldAlert, Sparkles, Trash2, Trophy } from "lucide-react";
import type { RoulettePrize } from "@/lib/roulette-store";

const iconOptions = [{ value: "crown", label: "VIP / корона", Icon: Crown }, { value: "coins", label: "Монети", Icon: CircleDollarSign }, { value: "gift", label: "Подарунок", Icon: Gift }, { value: "package", label: "Набір", Icon: Package }, { value: "trophy", label: "Зброя", Icon: Trophy }, { value: "sparkles", label: "Аватар / ефект", Icon: Sparkles }];
const blank = { label: "", icon: "gift" };

export default function AdminRoulette() {
  const [items, setItems] = useState<RoulettePrize[]>([]), [allowed, setAllowed] = useState<boolean | null>(null), [form, setForm] = useState(blank), [editing, setEditing] = useState<string | null>(null), [message, setMessage] = useState("");
  const load = () => fetch("/api/roulette/prizes", { cache: "no-store" }).then(r => r.json()).then(setItems);
  useEffect(() => { fetch("/api/auth/session").then(r => r.json()).then(async data => { if (!data.user) return setAllowed(false); const probe = await fetch("/api/roulette/prizes", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); setAllowed(probe.status !== 403); }).catch(() => setAllowed(false)); load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); const response = await fetch(editing ? `/api/roulette/prizes/${editing}` : "/api/roulette/prizes", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (response.ok) { setMessage(editing ? "Приз оновлено." : "Приз додано до рулетки."); setForm(blank); setEditing(null); load(); } else setMessage("Не вдалося зберегти приз."); };
  const remove = async (id: string) => { if (!confirm("Видалити цей приз із рулетки?")) return; await fetch(`/api/roulette/prizes/${id}`, { method: "DELETE" }); load(); };
  if (allowed === null) return <main className="shell py-20"><div className="panel animate-pulse p-10">Перевіряємо доступ...</div></main>;
  if (!allowed) return <main className="shell grid min-h-[65vh] place-items-center py-14"><div className="panel max-w-lg p-9 text-center"><ShieldAlert className="mx-auto text-ember" size={38} /><h1 className="heading mt-5 text-4xl">Доступ заборонено</h1></div></main>;
  return <main className="shell max-w-5xl py-14"><p className="eyebrow">Steam Admin · нагороди</p><h1 className="heading mt-2 text-5xl">Керування рулеткою</h1><p className="mt-4 text-sm text-stone-400">Саме ці призи відображаються на колесі. Після зміни онови сторінку рулетки.</p><section className="panel cut mt-8 p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#29351d]"><Plus className="text-[#c4da83]" /></span><h2 className="text-xl font-bold">{editing ? "Редагувати приз" : "Додати приз"}</h2></div><form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-[1fr_240px_auto]"><input required value={form.label} onChange={event => setForm(value => ({ ...value, label: event.target.value }))} className="min-w-0 bg-black/30 p-3" placeholder="Наприклад: VIP 30 днів" /><select value={form.icon} onChange={event => setForm(value => ({ ...value, icon: event.target.value }))} className="bg-[#121610] p-3">{iconOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select><button className="btn"><Save size={16} />{editing ? "Зберегти" : "Додати"}</button></form>{editing && <button onClick={() => { setEditing(null); setForm(blank); }} className="mt-3 text-sm text-[#c5d984]">Скасувати редагування</button>}{message && <p className="mt-4 text-sm text-[#c4da83]">{message}</p>}</section><section className="mt-10"><h2 className="heading text-3xl">Призи на колесі ({items.length})</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{items.map(item => { const Icon = iconOptions.find(option => option.value === item.icon)?.Icon || Gift; return <article key={item.id} className="panel cut flex items-center gap-4 p-5"><Icon className="text-[#c7da85]" /><p className="min-w-0 flex-1 truncate font-bold">{item.label}</p><button onClick={() => { setEditing(item.id); setForm({ label: item.label, icon: item.icon }); window.scrollTo({ top: 0, behavior: "smooth" }); }} className="btn !min-h-8 !px-3"><Pencil size={14} />Редагувати</button><button onClick={() => remove(item.id)} className="btn btn-outline !min-h-8 !px-3 !border-ember !text-red-300"><Trash2 size={14} /></button></article>; })}</div>{!items.length && <div className="panel mt-4 p-10 text-center text-stone-400">Призів ще немає.</div>}</section></main>;
}
